# -*- coding: utf-8 -*-
"""M25MAC005_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gJY2y4xP6pESUrI5h4EsLOoJh3M_Sim

# NLU Assignment — Problem 2
## Character-Level Name Generation with Sequence Models

This notebook implements and compares three sequence models for generating Indian names at the character level:
- **Vanilla RNN**
- **Bidirectional LSTM (BiLSTM)**
- **RNN with Attention**

All models are trained on the same **cleaned** list: title-cased **first + last** names from the LLM-generated file (`TrainingNames.txt`).
"""

import numpy as np
import random
import torch

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

"""---
## TASK 0 — Dataset

We use **Indian full names** from `TrainingNames.txt` (LLM-generated list, typically ~1000 lines). Entries are **normalized** to `Title Case**, and **only first + last** names (must contain a space) are kept so the character model matches realistic *Givenname Familyname* structure.
"""

with open("TrainingNames.txt", "r") as file_handle:
    raw_lines = file_handle.read().splitlines()

name_list = [entry.strip() for entry in raw_lines if entry.strip()]

clean_names = []
for n in name_list:
    n = n.strip()
    n = n.title()
    if " " not in n:
        continue
    clean_names.append(n)

name_list = clean_names

print(f"Dataset loaded: {len(name_list)} names (title-cased, first + last only).")
print("First 10 entries:", name_list[:10])

print("Total names in dataset:", len(name_list))
print("\nSample (first 20):", name_list[:20])

# Check for any duplicates
print("\nUnique names:", len(set(name_list)))

"""Building the Character Vocabulary

Since all three models work at the character level, the first step is to identify every unique character present in the dataset and assign each character a corresponding integer index.

Additionally, we include a special end-of-sequence token '.' in the vocabulary. This token helps the model understand where a name ends, enabling it to generate complete and well-formed outputs.
"""

# Collect all unique characters from every name in the dataset
all_chars = sorted(set("".join(name_list)))

# Append end-of-sequence marker — the model predicts this to signal name completion
all_chars.append(".")

# Build lookup dictionaries
ch2idx = {ch: idx for idx, ch in enumerate(all_chars)}
idx2ch = {idx: ch for ch, idx in ch2idx.items()}

num_tokens = len(all_chars)  # vocabulary size

print("Vocabulary size:", num_tokens)
print("Characters:", all_chars)

"""---
##Building the Character Vocabulary

All three models operate at the character level, so the process begins by identifying every unique character in the dataset and mapping each one to a corresponding integer index.

To help the model recognize when a name is complete, a special end-of-sequence token '.' is also added to the vocabulary. This allows the model to learn where a name ends and generate more accurate, well-structured outputs.
"""

encoded_sequences = []

for name in name_list:
    # Append EOS token so model learns where names terminate
    name_with_eos = name + "."

    # Map each character to its corresponding integer index
    seq = [ch2idx[c] for c in name_with_eos]
    encoded_sequences.append(seq)

# Verify encoding for the first name
print("Original name:", name_list[0])
print("Encoded sequence:", encoded_sequences[0])

"""---
## Preparing Input–Target Pairs

For next-character prediction, each encoded sequence is split into:
- **Input**: all characters except the last one
- **Target**: all characters except the first one (shifted by one position)

This forces the model to predict the next character at every step.
"""

seq_inputs = []
seq_targets = []

for seq in encoded_sequences:
    # Input: every token except the last
    seq_inputs.append(seq[:-1])

    # Target: every token except the first (one step ahead)
    seq_targets.append(seq[1:])

print("Input sequence (first name):", seq_inputs[0])
print("Target sequence (first name):", seq_targets[0])

import torch
from torch.nn.utils.rnn import pad_sequence

# Convert lists to tensors
input_tensor_list  = [torch.tensor(s, dtype=torch.long) for s in seq_inputs]
target_tensor_list = [torch.tensor(s, dtype=torch.long) for s in seq_targets]

# Pad to the length of the longest sequence in the batch
# padding_value=0 (will be ignored during loss computation via ignore_index=0)
padded_inputs  = pad_sequence(input_tensor_list,  batch_first=True, padding_value=0)
padded_targets = pad_sequence(target_tensor_list, batch_first=True, padding_value=0)

print("Padded input shape:",  padded_inputs.shape)
print("Padded target shape:", padded_targets.shape)

import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import random


def clean_sample(char, generated):
    """Lowercase stray uppercase inside a segment; keep uppercase at string start or after a space."""
    if not char.isalpha():
        return char
    if not char.isupper():
        return char
    if len(generated) == 0 or generated[-1] == " ":
        return char
    return char.lower()

"""---
## TASK 1 — Model Implementations

---
### Model 1: Vanilla RNN

**Architecture:**  
A standard recurrent network that processes the input character sequence one step at a time. At each timestep, the hidden state is updated based on the current input and the previous hidden state.

**Layers:**
1. `Embedding` — maps each character index to a dense vector of size `hidden_dim`
2. `RNN` — single-layer recurrent unit (tanh activation)
3. `Linear` — projects the hidden state to vocabulary-sized logits for next-character prediction

**Limitation:** Vanilla RNNs suffer from vanishing gradients over long sequences, making it difficult to model long-range character dependencies.
"""

class SimpleRNN(nn.Module):

    def __init__(self, vocab_sz, hidden_dim):
        super(SimpleRNN, self).__init__()

        # Character embedding: converts token index to a learnable dense vector
        self.embed = nn.Embedding(vocab_sz, hidden_dim)

        # Core RNN layer — single direction, single layer
        self.rnn_layer = nn.RNN(hidden_dim, hidden_dim, batch_first=True)

        # Projection head: maps hidden states to next-character probabilities
        self.output_proj = nn.Linear(hidden_dim, vocab_sz)

    def forward(self, token_ids):

        # Step 1: Look up embeddings for each token
        emb = self.embed(token_ids)              # (batch, seq_len, hidden_dim)

        # Step 2: Run through the recurrent layer
        hidden_states, _ = self.rnn_layer(emb)   # (batch, seq_len, hidden_dim)

        # Step 3: Project to vocabulary logits
        logits = self.output_proj(hidden_states)  # (batch, seq_len, vocab_sz)

        return logits

HIDDEN_DIM    = 128
LEARNING_RATE = 0.001
NUM_EPOCHS    = 80

rnn_model = SimpleRNN(num_tokens, HIDDEN_DIM)

# CrossEntropyLoss with ignore_index=0 so padded positions don't affect training
loss_fn = nn.CrossEntropyLoss(ignore_index=0)

# Adam optimizer — adaptive learning rate, works well for sequence tasks
rnn_optimizer = optim.Adam(rnn_model.parameters(), lr=LEARNING_RATE)

print(rnn_model)

rnn_param_count = sum(p.numel() for p in rnn_model.parameters() if p.requires_grad)
print(f"Vanilla RNN — Trainable Parameters: {rnn_param_count:,}")

for epoch in range(NUM_EPOCHS):

    # Clear accumulated gradients from the previous iteration
    rnn_optimizer.zero_grad()

    # Forward pass: predict next character at every timestep
    predictions = rnn_model(padded_inputs)        # (batch, seq_len, vocab)

    # Flatten to (batch*seq_len, vocab) for loss computation
    flat_preds   = predictions.reshape(-1, num_tokens)
    flat_targets = padded_targets.reshape(-1)

    # Compute cross-entropy loss (padded positions ignored)
    batch_loss = loss_fn(flat_preds, flat_targets)

    # Backpropagate gradients through time
    batch_loss.backward()

    torch.nn.utils.clip_grad_norm_(rnn_model.parameters(), 5)

    # Update model weights
    rnn_optimizer.step()

    print(f"Epoch [{epoch+1:02d}/{NUM_EPOCHS}]  Loss: {batch_loss.item():.4f}")

"""---
### Generating Names — Vanilla RNN

Names are generated autoregressively from a random uppercase seed using **temperature 0.5**, `clean_sample` (no stray capitals inside a segment), a **space** after a random first-name length in `[3, 6]`, early stopping when **`.`** is sampled, and an optional **length** stop (`len > 12`, 30% chance) to limit run-on gibberish. The same recipe is used for BiLSTM and RNN+Attention so comparisons are fair.
"""

def sample_name_rnn(mdl, temp=0.5, max_len=25):
    """
    Autoregressively generates a full Indian name (first + last)
    using the trained Vanilla RNN.
    Args:
        mdl     : trained SimpleRNN model
        temp    : temperature for sampling (lower → sharper distribution)
        max_len : maximum number of characters to generate
    """
    mdl.eval()

    seed_char = random.choice([c for c in ch2idx if c.isupper()])
    generated = seed_char
    current_input = torch.tensor([[ch2idx[seed_char]]], dtype=torch.long)

    inserted_space = False
    space_after_len = random.randint(3, 6)

    for _ in range(max_len):

        with torch.no_grad():
            out = mdl(current_input)

        scaled_logits = out[0, -1] / temp
        char_probs = F.softmax(scaled_logits, dim=0)

        sampled_idx = torch.multinomial(char_probs, 1).item()
        sampled_char = idx2ch[sampled_idx]

        if not inserted_space and len(generated) > space_after_len:
            sampled_char = " "
            inserted_space = True

        if sampled_char == ".":
            break

        if sampled_char != " ":
            sampled_char = clean_sample(sampled_char, generated)

        generated += sampled_char

        if len(generated) > 12 and random.random() < 0.3:
            break

        next_tok = torch.tensor([[ch2idx.get(sampled_char, sampled_idx)]])
        current_input = torch.cat((current_input, next_tok), dim=1)

    return generated.strip()

def generate_eval_pool(sample_fn, model, num_samples=500):
    raw = [sample_fn(model) for _ in range(num_samples)]

    filtered = []
    for n in raw:
        parts = n.split()
        if len(parts) == 2 and len(parts[0]) > 2 and len(parts[1]) > 2 and len(n) > 6:
            filtered.append(n)

    return filtered


rnn_display = generate_eval_pool(sample_name_rnn, rnn_model, num_samples=200)
rnn_display = list(dict.fromkeys(rnn_display))[:30]

print("Sample generated names (Vanilla RNN):")
rnn_display

"""---
## TASK 2 — Quantitative Evaluation: Vanilla RNN

We evaluate generated names using two metrics:

| Metric | Definition |
|---|---|
| **Novelty Rate** | Fraction of generated names *not* found in the training set |
| **Diversity** | Fraction of *unique* names among all generated names |
"""

rnn_eval_pool = generate_eval_pool(sample_name_rnn, rnn_model)
print(f"RNN evaluation pool: {len(rnn_eval_pool)} valid names (from 500 raw samples).")

train_name_set = set(name_list)  # fast O(1) lookup

rnn_novel = [n for n in rnn_eval_pool if n not in train_name_set]
novelty_rnn = len(rnn_novel) / len(rnn_eval_pool) if rnn_eval_pool else 0

print(f"Vanilla RNN — Novelty Rate: {novelty_rnn:.4f}")

diversity_rnn = len(set(rnn_eval_pool)) / len(rnn_eval_pool) if rnn_eval_pool else 0

print(f"Vanilla RNN — Diversity: {diversity_rnn:.4f}")

"""**Observation — Vanilla RNN:**  
The model captures basic character-level patterns. A novelty rate near 1.0 confirms it is not memorising training names. Diversity captures how varied the outputs are — lower diversity means the model tends to repeat the same patterns.

---
### Model 2: Bidirectional LSTM (BiLSTM)

**Architecture:**  
Unlike a vanilla RNN, an LSTM uses gating mechanisms (input, forget, and output gates) to selectively retain or discard information, effectively solving the vanishing gradient problem.

Adding **bidirectionality** means the model reads the sequence in both directions simultaneously. At each timestep the forward and backward hidden states are concatenated, giving the model access to both left and right context — a richer representation than a unidirectional model.

**Layers:**
1. `Embedding` — character index → dense vector
2. `LSTM (bidirectional)` — forward + backward hidden states concatenated
3. `Linear` — projects the `2 × hidden_dim` concatenated state to vocab logits
"""

class BiLSTMNet(nn.Module):

    def __init__(self, vocab_sz, hidden_dim):
        super(BiLSTMNet, self).__init__()

        # Character-level embedding table
        self.embed = nn.Embedding(vocab_sz, hidden_dim)

        # Bidirectional LSTM — two directions, states are concatenated
        self.bilstm = nn.LSTM(
            input_size=hidden_dim,
            hidden_size=hidden_dim,
            batch_first=True,
            bidirectional=True    # forward pass + backward pass
        )

        # Output projection: input is 2*hidden_dim due to bidirectional concatenation
        self.classifier = nn.Linear(hidden_dim * 2, vocab_sz)

    def forward(self, token_ids):

        # Embed character tokens
        emb = self.embed(token_ids)                # (batch, seq_len, hidden_dim)

        # Pass through bidirectional LSTM
        lstm_out, _ = self.bilstm(emb)             # (batch, seq_len, 2*hidden_dim)

        # Project to vocabulary logits
        logits = self.classifier(lstm_out)         # (batch, seq_len, vocab_sz)

        return logits

hidden_dim_bilstm = 128
lr_bilstm         = 0.001
epochs_bilstm     = 80

bilstm_model = BiLSTMNet(num_tokens, hidden_dim_bilstm)

# Shared loss function — padded positions excluded
loss_fn_bilstm = nn.CrossEntropyLoss(ignore_index=0)

# Adam optimizer
bilstm_optimizer = optim.Adam(bilstm_model.parameters(), lr=lr_bilstm)

print(bilstm_model)

bilstm_param_count = sum(p.numel() for p in bilstm_model.parameters() if p.requires_grad)
print(f"BiLSTM — Trainable Parameters: {bilstm_param_count:,}")

for epoch in range(epochs_bilstm):

    bilstm_optimizer.zero_grad()

    # Forward pass
    preds = bilstm_model(padded_inputs)          # (batch, seq_len, vocab)

    # Flatten for loss
    flat_preds   = preds.reshape(-1, num_tokens)
    flat_targets = padded_targets.reshape(-1)

    epoch_loss = loss_fn_bilstm(flat_preds, flat_targets)

    epoch_loss.backward()
    torch.nn.utils.clip_grad_norm_(bilstm_model.parameters(), 5)
    bilstm_optimizer.step()

    print(f"Epoch [{epoch+1:02d}/{epochs_bilstm}]  Loss: {epoch_loss.item():.4f}")

"""---
### Generating Names — BiLSTM

The generation procedure matches the vanilla RNN helper: **temperature 0.5**, `clean_sample`, variable first-name length before the space, EOS **`.`**, and optional length-based early stopping.
"""

def sample_name_bilstm(mdl, temp=0.5, max_len=25):
    """
    Generates an Indian full name using the trained BiLSTM model.
    The generation is fully model-driven — no real training names are used as seeds.
    """
    mdl.eval()

    seed_char = random.choice([c for c in ch2idx if c.isupper()])
    generated = seed_char
    current_input = torch.tensor([[ch2idx[seed_char]]], dtype=torch.long)

    inserted_space = False
    space_after_len = random.randint(3, 6)

    for _ in range(max_len):

        with torch.no_grad():
            out = mdl(current_input)

        scaled = out[0, -1] / temp
        probs = F.softmax(scaled, dim=0)
        chosen_idx = torch.multinomial(probs, 1).item()
        chosen_char = idx2ch[chosen_idx]

        if not inserted_space and len(generated) > space_after_len:
            chosen_char = " "
            inserted_space = True

        if chosen_char == ".":
            break

        if chosen_char != " ":
            chosen_char = clean_sample(chosen_char, generated)

        generated += chosen_char

        if len(generated) > 12 and random.random() < 0.3:
            break

        next_tok = torch.tensor([[ch2idx.get(chosen_char, chosen_idx)]])
        current_input = torch.cat((current_input, next_tok), dim=1)

    return generated.strip()

bilstm_eval_pool = generate_eval_pool(sample_name_bilstm, bilstm_model)
print(f"BiLSTM evaluation pool: {len(bilstm_eval_pool)} valid names (from 500 raw samples).")

bilstm_display = list(dict.fromkeys(bilstm_eval_pool))[:30]

print("Sample generated names (BiLSTM):")
bilstm_display

"""---
## TASK 2 — Quantitative Evaluation: BiLSTM
"""

bilstm_novel = [n for n in bilstm_eval_pool if n not in train_name_set]
novelty_bilstm = len(bilstm_novel) / len(bilstm_eval_pool) if bilstm_eval_pool else 0

print(f"BiLSTM — Novelty Rate: {novelty_bilstm:.4f}")

diversity_bilstm = len(set(bilstm_eval_pool)) / len(bilstm_eval_pool) if bilstm_eval_pool else 0

print(f"BiLSTM — Diversity: {diversity_bilstm:.4f}")

"""**Observation — BiLSTM:**  
The gating mechanism of LSTM helps retain character dependencies over longer name segments. Bidirectionality provides both past and future context at training time, which can improve the quality and fluency of generated names.

---
### Model 3: RNN with Attention Mechanism

**Architecture:**  
The RNN produces a hidden state each step. **Causal dot-product attention** builds, at position `t`, a context vector over **past positions only** (`j ≤ t`), with keys/values taken from those same RNN hiddens (Luong-style self-attention over the prefix). That context is **different at every timestep** — unlike a single global vector repeated across time, which makes logits nearly identical and encourages degenerate loops (`aaa…`). Padding keys are masked out. A linear layer fuses `[h_t ; context_t]` before the vocab projection.
"""

class RNNWithAttention(nn.Module):

    def __init__(self, vocab_sz, hidden_dim, dropout=0.15):
        super(RNNWithAttention, self).__init__()

        self.hidden_dim = hidden_dim
        self.scale = hidden_dim ** 0.5
        self.embed = nn.Embedding(vocab_sz, hidden_dim)
        self.rnn_core = nn.RNN(hidden_dim, hidden_dim, batch_first=True)
        self.fuse = nn.Linear(hidden_dim * 2, hidden_dim)
        self.dropout = nn.Dropout(dropout)
        self.output_layer = nn.Linear(hidden_dim, vocab_sz)

    def forward(self, token_ids):

        emb = self.embed(token_ids)
        h, _ = self.rnn_core(emb)
        B, T, H = h.shape

        scores = torch.bmm(h, h.transpose(1, 2)) / self.scale

        causal = torch.triu(torch.ones(T, T, device=h.device, dtype=torch.bool), diagonal=1)
        scores = scores.masked_fill(causal, float("-inf"))

        key_pad = token_ids == 0
        scores = scores.masked_fill(key_pad.unsqueeze(1).expand(B, T, T), float("-inf"))

        attn = torch.softmax(scores, dim=-1)
        attn = torch.nan_to_num(attn, nan=0.0)

        context = torch.bmm(attn, h)
        fused = self.dropout(torch.tanh(self.fuse(torch.cat([h, context], dim=-1))))
        logits = self.output_layer(fused)
        return logits

hidden_dim_attn = 128
lr_attn         = 0.001
epochs_attn     = 80

attn_model = RNNWithAttention(num_tokens, hidden_dim_attn)

loss_fn_attn    = nn.CrossEntropyLoss(ignore_index=0)
attn_optimizer  = optim.Adam(attn_model.parameters(), lr=lr_attn)

print(attn_model)

attn_param_count = sum(p.numel() for p in attn_model.parameters() if p.requires_grad)
print(f"RNN + Attention — Trainable Parameters: {attn_param_count:,}")

for epoch in range(epochs_attn):

    attn_optimizer.zero_grad()

    # Forward pass through the attention-augmented RNN
    preds = attn_model(padded_inputs)

    flat_preds   = preds.reshape(-1, num_tokens)
    flat_targets = padded_targets.reshape(-1)

    epoch_loss = loss_fn_attn(flat_preds, flat_targets)

    epoch_loss.backward()
    torch.nn.utils.clip_grad_norm_(attn_model.parameters(), 5)
    attn_optimizer.step()

    print(f"Epoch [{epoch+1:02d}/{epochs_attn}]  Loss: {epoch_loss.item():.4f}")

"""---
### Generating Names — RNN with Attention
"""

def _repeat_streak_len(s):
    if not s:
        return 0
    c, n = s[-1], 1
    for i in range(len(s) - 2, -1, -1):
        if s[i] == c:
            n += 1
        else:
            break
    return n


def _logits_with_repeat_penalty(logits, generated, max_streak=2, penalty=7.0):
    logits = logits.clone()
    if len(generated) < 1:
        return logits
    last = generated[-1]
    if last not in ch2idx or last in (" ", "."):
        return logits
    if _repeat_streak_len(generated) < max_streak:
        return logits
    logits[ch2idx[last]] -= penalty
    return logits


def sample_name_attn(mdl, temp=0.4, max_len=22):
    """
    RNN+Attention: slightly sharper temp + repeat penalty to avoid aaaaa / ooooo loops.
    """
    mdl.eval()

    seed_char = random.choice([c for c in ch2idx if c.isupper()])
    generated = seed_char
    current_input = torch.tensor([[ch2idx[seed_char]]], dtype=torch.long)
    inserted_space = False
    space_after_len = random.randint(3, 6)

    for _ in range(max_len):

        with torch.no_grad():
            out = mdl(current_input)

        logits = out[0, -1].float()
        logits = _logits_with_repeat_penalty(logits, generated)
        probs = F.softmax(logits / temp, dim=0)

        chosen_idx = torch.multinomial(probs, 1).item()
        chosen_char = idx2ch[chosen_idx]

        if not inserted_space and len(generated) > space_after_len:
            chosen_char = " "
            inserted_space = True

        if chosen_char == ".":
            break

        if chosen_char != " ":
            chosen_char = clean_sample(chosen_char, generated)

        generated += chosen_char

        if len(generated) > 11 and random.random() < 0.35:
            break

        next_tok = torch.tensor([[ch2idx.get(chosen_char, chosen_idx)]])
        current_input = torch.cat((current_input, next_tok), dim=1)

    return generated.strip()

attn_eval_pool = generate_eval_pool(sample_name_attn, attn_model)
print(f"RNN + Attention evaluation pool: {len(attn_eval_pool)} valid names (from 500 raw samples).")

attn_display = list(dict.fromkeys(attn_eval_pool))[:30]

print("Sample generated names (RNN + Attention):")
attn_display

"""---
## TASK 2 — Quantitative Evaluation: RNN with Attention
"""

attn_novel   = [n for n in attn_eval_pool if n not in train_name_set]
novelty_attn = len(attn_novel) / len(attn_eval_pool) if attn_eval_pool else 0

print(f"RNN + Attention — Novelty Rate: {novelty_attn:.4f}")

diversity_attn = len(set(attn_eval_pool)) / len(attn_eval_pool) if attn_eval_pool else 0

print(f"RNN + Attention — Diversity: {diversity_attn:.4f}")

"""---
## Final Comparison — All Three Models

The table below summarises the key metrics across all three models trained on the same dataset of Indian names.

**Evaluation consistency:** novelty and diversity are computed on outputs from the same helper, `generate_eval_pool` (500 samples each, identical filtering rules), so comparisons across models are fair.
"""

print("=" * 65)
print(f"{'Model':<25} {'Params':>10} {'Novelty Rate':>14} {'Diversity':>12}")
print("=" * 65)
print(f"{'Vanilla RNN':<25} {rnn_param_count:>10,} {novelty_rnn:>14.4f} {diversity_rnn:>12.4f}")
print(f"{'BiLSTM':<25} {bilstm_param_count:>10,} {novelty_bilstm:>14.4f} {diversity_bilstm:>12.4f}")
print(f"{'RNN + Attention':<25} {attn_param_count:>10,} {novelty_attn:>14.4f} {diversity_attn:>12.4f}")
print("=" * 65)

print("\nParameter Interpretation:")
print("BiLSTM has more parameters due to bidirectional structure.")
print("Attention model adds additional parameters for attention scoring.")

print("\n=== QUANTITATIVE ANALYSIS INTERPRETATION ===")
print("High novelty rate (~1.0) indicates models are not memorizing training data.")
print("Diversity reflects how varied the generated names are.")
print("BiLSTM often leads on fluency due to gating and bidirectional training context.")
print("RNN + Attention uses a weighted sum over time; with correct attention it should not collapse to vanilla RNN behaviour.")

print("\n=== MODEL COMPARISON ANALYSIS ===")
print("Vanilla RNN: weakest long-range structure; prone to noisy suffixes without strong regularization.")
print("BiLSTM: stronger sequence modeling; often clearer syllable-like chunks from bidirectional context.")
print("RNN + Attention: global context vector per step can improve coherence vs. unweighted RNN states.")
print("Fair comparison uses the same epochs, lr, clipping, data cleaning, and decoding recipe.")

print("\n=== SAMPLE QUALITY ANALYSIS ===")
print("Good outputs: plausible Indian-like vowel–consonant runs and short surnames.")
print("Weak outputs before fixes: random capitals inside tokens, long gibberish tails, poor EOS behaviour.")

print("\n=== FAILURE MODE ANALYSIS (what to cite in the report) ===")
print("1. Character noise / gibberish suffixes — e.g. fragments like 'TbkMkDNPyGYKl' — weak sequence + no length/EOS control.")
print("2. Unnatural capitalization — uppercase mid-token — model learns marginal char distribution, not segment structure; mitigated by clean_sample + title-cased data.")
print("3. Overgeneration — very long names when '.' is unlikely — mitigated by EOS training, length stop, temperature.")
print("4. Phonetic inconsistency — not Indian-like syllables — noisy LLM data + limited capacity; cleaning helps.")
print("5. Attention ineffectiveness — if attention is wrong (softmax over hidden dims + element-wise mul), attend RNN ≈ vanilla RNN; fixed by scalar scores + softmax over time + weighted sum.")

"""---
## Discussion

| Model | Strengths | Weaknesses |
|---|---|---|
| **Vanilla RNN** | Simple, fast to train, fewest parameters | Prone to vanishing gradients; may struggle with longer names |
| **BiLSTM** | Gating controls long-range dependencies; bidirectional context | More parameters; slower to train |
| **RNN + Attention** | Global attention over all past hidden states (weighted sum, then decode) | Heavier compute; quality depends on correct attention (time-softmax + pooling) |

A **novelty rate close to 1.0** indicates the model is generating genuinely new names rather than copying from the training set.  
A **higher diversity score** means the model produces a wider variety of names, suggesting it has learned the underlying character distribution rather than collapsing to a few common patterns.
"""